name: Build

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - ".github/workflows/build.yaml"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "**.go"
      - "**.go.json"
      - "Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build.yaml"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "**.go"
      - "**.go.json"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.18.0"

      - name: Go Build Cache (build)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: go-cache-1-${{ hashFiles('**/go.sum') }}-build
          restore-keys: |
            go-cache-1-${{ hashFiles('**/go.sum') }}-
            go-cache-1-

      - run: go get ./...

      - name: Build
        run: make build

      - run: docker build .
