name: release

on:
  push:
    branches:
      - python

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Tag Name
        run: echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build --build-arg "COMMIT_REF=$SHA" -t ghcr.io/bangumi/api-server:latest .

      - run: echo $DOCKER_TOKEN | docker login ghcr.io -u bangumi --password-stdin
        name: docker login
        env:
          DOCKER_TOKEN: ${{ github.token }}

      - run: |
          docker push ghcr.io/bangumi/api-server:latest
          docker push "ghcr.io/bangumi/api-server:python-$SHA"
        name: Docker Push
